### PR TITLE
Add Rust CI

### PR DESCRIPTION
**Pull request by sanders41**

### CODE REVIEW

**Comment by prrao87** [comment]
Haha seems like I forgot to run `cargo fmt` prior to my last commit 😂
Shows the importance of CI, I guess!

**Comment by sanders41** [comment]
The weird thing is when I run it locally it passes. Debugging github actions drives me crazy! You just have to push and see what happens.

**Comment by prrao87** [comment]
@sanders41 the test errors are more serious, but I don't see how we'd fix that because the sqlx `query!` macro requires that the database connection exists and is valid prior to compilation. But in CI, we don't have a database on the runner. Can we disable the checks just for that?

**Comment by sanders41** [comment]
This step sets everything up and is working locally, I'm trying to figure out why CI isn't happy with it.

```yaml
      - name: Prep data # This prevents sqlx errors if the database isn't running
        run: sh ./scripts/prep_tests.sh
```

**Comment by prrao87** [comment]
Yup, I also always hated debugging GitHub actions! It's among the worst developer experience one can see these days.

**Comment by sanders41** [comment]
For the format error it really was that the formatter needed running after I merged main. For Clippy and testing sqlx is definitely winning this battle so far :smile: . I've tried all kinds of things and so far nothing makes it happy.

I'm stubborn though, I'm not giving up yet!

**Comment by sanders41** [comment]
_FINALLY_ I got it to work. The last piece keeping things from working was I needed to create the scripts/data directory before copying the file. This was causing the docker startup to fail, but it didn't show up in the GH actions log.

**Comment by prrao87** [comment]
Nice! Glad it worked out after all that effort!

Do you normally prune old branches in bulk or keep them for a few days? I just tend to keep things clean and have the fewest branches possible.

**Comment by sanders41** [comment]
Actually I usually turn on the setting that auto deletes the branches when they merge. I just forgot to delete this one.

**Comment by prrao87** [comment]
I wasn't aware there was such a setting 😂 And I was surprised someone so meticulous as you would keep unused branches lying around, I should have known there was a better way and just asked you! I'll activate that setting.

**Pull request merged**
