### PR TITLE
Rename scripts directory to ci

### PR DESCRIPTION
**Pull request by prrao87**
@sanders41 the directory name `scripts` in the root level of the repo is a bit misleading and can cause folks to think it's necessary to use in the pieces directory (which actually has the code). I've renamed it to `ci` to be more explicit so that visitors who are checking out the repo don't mistakenly click on it thinking there's useful code in there.

Could you verify that there's nothing that's broken as a result of this name change? I suppose the CI itself will tell us something.

### CODE REVIEW

**Comment by prrao87** [comment]
Alternately, if the `ci` directory isn't required for any other purpose (which it shouldn't), does it make sense to move it to the `.github.` directory and update the paths accordingly? The root level would ideally have just the `pieces` and the `book` sections to make it clear what's where to a new visitor.

**Review by sanders41 — APPROVED** [review]
Everything looks good here. I didn't really like the name scripts since it has things like docker-compose files also.

**Comment by prrao87** [comment]
Alright, let me merge this and we can see later on about how it looks once the book's CI goes in.

**Comment by sanders41** [comment]
> Alternately, if the ci directory isn't required for any other purpose (which it shouldn't), does it make sense to move it to the .github directory and update the paths accordingly? The root level would ideally have just the pieces and the book sections to make it clear what's where to a new visitor.

This is a good question. I wasn't sure if putting it in the .github directory would cause any issues since it is a special directory. We could try it and see what happens. It should be quickly apparent if it works.

**Comment by prrao87** [comment]
Will give this a try once I push the book PR 👍🏽

**Pull request merged**
