### PR TITLE
Add dob column and processing

### LINKED ISSUE #10: Update `modify_csv` piece to showcase `chrono` crate
The current versions of the `modify_csv` projects in Python and Rust are too simplistic. All that's done is that we read in a CSV of persons, and add the `id` field to each record, and we then write out a new CSV file with the new records. While this introduces file-handling concepts in Rust, it would be more useful to demonstrate a more substantial feature of the Rust landscape, like datetime handling.

Here's the idea:

- The input CSV would now have a `datetime` field (like year of birth) in the wrong format (`mm-dd-yyyy`)
- The output CSV would require the `datetime` fields in the ISO format (`yyyy-mm-dd`)
    - This would be a golden opportunity to introduce the [`chrono`](https://crates.io/crates/chrono) crate in Rust

`modify_csv` would be the first piece after the `intro` piece, which builds on basic data structures and introduces the reader to the Rust [crates.io](https://crates.io/) ecosystem.

## What needs to be done:

- [x] Redo the [Python](https://github.com/thedataquarry/rustinpieces/tree/main/python/modify_csv) code base to handle datetimes (dates of birth) from the raw CSVs
- [x] Redo the [Rust](https://github.com/thedataquarry/rustinpieces/tree/main/rust/modify_csv) code base to handle datetimes via the `chrono` crate, similar to Python
- [x] Update the docs in both locations to describe the difference between the Python `datetime` module (which is in the standard library) and the Rust `chrono` crate, which must be installed via Cargo.

### PR DESCRIPTION
**Pull request by sanders41**
Closes #10

@prrao87 I didn't see you assigned this one to yourself until just now so feel free to close this one if you were already working on something.

### CODE REVIEW

**Comment by prrao87** [comment]
No this is great! Feel free to add a PR anytime if you're looking into it 😄

**Comment by sanders41** [comment]
I updated the README files with an explanation of the difference in standard library Python and Rust crates for the datetimes. Hopefully I explained it well, but if you think we need something different let me know.

**Comment by prrao87** [comment]
This code is great, but I was thinking about this, and I think the problem statement might have been framed too ambitiously 😅... This is a great example of why Rust is non-trivial for people coming from interpreted languages. Just this small deserializer snippet has *immense* complexity and is really hard to read for a beginner.

```rust
fn date_deserializer<'de, D>(deserializer: D) -> Result<Option<NaiveDate>, D::Error>
where
    D: Deserializer<'de>,
{
    let date_str: Option<String> = Option::deserialize(deserializer)?;

    match date_str {
        Some(d) => NaiveDate::parse_from_str(&d, INPUT_DATE_FORMAT)
            .map_err(serde::de::Error::custom)
            .map(Some),
        None => NaiveDate::from_ymd_opt(1970, 1, 1)
    }
}
```

To be able to understand this code as a beginner in Rust, the following things need are required knowledge:

- What deserialization/serialization is, and why they're necessary in a lower level language like Rust
- Lifetime annotations and `where` sugar syntax to handle complex types
- Result (`Ok`) and Option enums with `Some` and `None` variants
- Complex error handling with error propagation using `?`
- Match statement to catch all result and option types
- Mapping custom error types

Whew! Way too much to explain to someone who's just starting off, even if they've read the Rust book. I think it makes sense to keep this, but in a new directory and moved to much later in the book. I'm thinking the proposal below makes sense.

## Proposal

- The `chrono` crate and datetime parsing are still important tasks in their own right, so these concepts deserve their own piece, but introducing lifetime annotations, complex error handling and all this added complexity early on to an inexperienced Rust programmer is overkill.
- It makes sense to keep this piece, but rename the parent directory to `datetime_parsing_csv`, and make this a more intermediate piece to be introduced at a later time (the `regex_json` piece is far simpler to get acquainted with the crate ecosystem, and so can be introduced immediately after the `intro` piece)
- Write a simpler piece `simple_parsing_csv` where we take a much simpler CSV file, and introduce structs, serialization and deserialization with simple string/integer/float handling and how to work with CSVs
- The layout of the pieces can be reorganized into a form that covers concepts from the Rust book (structs, enums, etc., with lifetimes coming later on)

I really think that lifetimes is one of the hardest concepts in Rust, and even code with lifetime annotations make it very intimidating to new users. So I was hoping to introduce code that uses lifetimes later on.

**Comment by sanders41** [comment]
I agree with you here :100:. The difference in `new_item["dob"] = (datetime.strptime(item["dob"], "%m-%d-%Y").date() if item.get("dob") else None)` in the python version to the rust version is likely to scare people off if this is presented as a "simple" concept early on.

**Comment by prrao87** [comment]
Yup! I also had the idea that using this datetime CSV parsing later on is a great point to introduce Polars, which makes this sort of thing far easier in both Rust and Python (not to mention more scalable). So I've redone the docs and reorged the pieces accordingly.

**Comment by prrao87** [comment]
I've cleaned up the tests and made the Python/Rust functions more similar (as far as possible). Merging this and closing #10

**Pull request merged**
