### PR TITLE
Add python parallel processing intro example

### PR DESCRIPTION
**Pull request by sanders41**

### CODE REVIEW

**Comment by sanders41** [comment]
The mock data is really just to give a second task to work on. So the data is generated sequentially, but the generation is in one thread and the spinner is in another. This allows the spinner to display and the data to be generated at the same time.  Otherwise one happens, then the other. I wanted something that took a while so you could see both happening at the same time which is why I used the data generation. The other idea here is to show how to pass messages between the treads/processes.

Though honestly I had a hard time cominig up with a good example here so if you have better ideas I'm not set on this one :smile: .

**Comment by prrao87** [comment]
Ah, that makes sense. Though, I think what you're showing here wasn't the real intent of the "parallel processing" section 😅. 

I'll write up my thoughts as a discussion.

**Comment by sanders41** [comment]
My thinking was in the context of an application, but I don't think my example does a good job of illustrating it. Let's say the application has a computation heavy process. If you run that computation in the same thread the application will freeze until it is complete. By moving the work to a thread the rest of the application can stay responsive.

**Comment by prrao87** [comment]
Yeah I don't think that would be termed "parallelization" in the true sense. It's just the ability to perform concurrent tasks that aren't blocked by the same process? I'm more thinking along the lines of embarrassingly parallel problems, in which Rayon will truly shine. I'm just sharing my thoughts in the discussion now..

**Comment by prrao87** [comment]
My concern with this piece is that it's deviating from the "top-down" methodology by attempting to demonstrate low level concepts (like mutexes, Arc and threads) without a realistic problem statement. In the real-world, people would simply `import rich` or `use indicatif` and avoid thinking about the implementation details.

We do the same in the `sqlx` example too: We didn't introduce the concept of Arc bottom-up, but rather use it as part of how `sqlx` uses it, which is how a lot of people begin to learn how to use Arc (rather than working with mutexes, which are notoriously hard for the average person).

I do like that you introduced the `anyhow` crate here though, so that got me wondering, are there specific reasons why we'd use `anyhow` over the standard error handling in Rust? Also, one of Rust's most amazing features that's far better than Python is error handling, so it would be fabulous to do a piece on handling errors the standard way, and then using `anyhow`, and contrasting that with the relatively basic error handling that you can do in Python. What do you think about closing this one and focusing on that instead? I can take on the Rayon parallelism task, no issues there.

**Comment by sanders41** [comment]
An anyhow `Result` is similar to using `Box<dyn std::error::Error>`, but I believe it is actually a little lighter weight. anyhow also provides some other nice functionality like `bail!` that lets you return an error and exit the function early. It is super common to use anyhow, I see it more than using the standard `Result` with `Box<dyn std::error::Error>`.

The other common thing to see all the time with errors in libraries is to use [thiserror](https://github.com/dtolnay/thiserror) because it lets you easily make custom errors.

**Pull request closed without merging**
